/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef __VIPSDISP_MARSHAL_H__
#define __VIPSDISP_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID: POINTER, INT (vipsdispmarshal.list:25) */
extern void vipsdisp_VOID__POINTER_INT(GClosure *closure,
	GValue *return_value,
	guint n_param_values,
	const GValue *param_values,
	gpointer invocation_hint,
	gpointer marshal_data);

G_END_DECLS

#endif /* __VIPSDISP_MARSHAL_H__ */
